name: MLGRush
version: 1.0
author: DelfikPro
main: pro.delfik.mlg.MLGRush
softdepend: [LMAONetwork, ImplarioLib]
commands:
  mlgrush:
    aliases: [mlg]
  stickfight:
    aliases: [palka, sf]
  capitulate:
    aliases: [c]